name: Clients deployment

on:
  push:
    branches: [ "clients-main" ]

env:
  SERVICE_NAME: clients
  RESOURCE_GROUP: construction-company-rg

jobs:
  Clients:
    name: Clients deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: clients
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
      - name: Install az containerapp extension
        run: |
          az config set extension.use_dynamic_install=yes_without_prompt
      - name: ACR Login
        uses: azure/docker-login@v1
        with:
          login-server: contoso.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}  
      - name: Get today date
        run: |
          TODAY_DATE_TAG=$(date +"%Y-%m-%dT%H-%M-%S")
          echo "TODAY_DATE_TAG=$TODAY_DATE_TAG" >> $GITHUB_ENV
      - name: Build Docker Python image
        run: | 
          docker build --platform linux --tag constructioncompanyacr.azurecr.io/clients:$TODAY_DATE_TAG -f .
      - name: Publish Docker Python image
        run: |
          docker push constructioncompanyacr.azurecr.io/clients:$TODAY_DATE_TAG
      - name: Deploy Python container App
        run: |
          az containerapp up --name "$SERVICE_NAME" --resource-group $RESOURCE_GROUP --environment microservices-env --image constructioncompanyacr.azurecr.io/clients:$TODAY_DATE_TAG --ingress external --target-port 80
